# Generated by Django 4.2.11 on 2025-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-created"],
                "verbose_name": "Controller entry",
                "verbose_name_plural": "Controllers entries",
            },
        ),
        migrations.AlterModelOptions(
            name="slot",
            options={
                "ordering": ["position"],
                "verbose_name": "Controller slot",
                "verbose_name_plural": "Controllers slots",
            },
        ),
        migrations.AlterField(
            model_name="slot",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
    ]
