# Generated by Django 5.2.1 on 2025-06-28 01:30

import django.db.models.deletion
from django.db import migrations, models

from ..choices import get_controller_handler_choices, get_controller_handler_default


class Migration(migrations.Migration):

    dependencies = [
        ('canopy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=get_controller_handler_choices(), default=get_controller_handler_default(), help_text='Handler type.', max_length=255, verbose_name='name')),
                ('controller', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='canopy.controller')),
            ],
            options={
                'verbose_name': 'Data handler',
                'verbose_name_plural': 'Data handlers',
                'ordering': ['controller', 'name'],
            },
        ),
    ]
