# Generated by Django 4.2.11 on 2025-03-04 16:25

import canopy.models.entry
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopy", "0002_alter_entry_options_alter_slot_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="data",
            field=models.JSONField(
                default=canopy.models.entry.empty_fresh_dictionnary,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
