# Generated by Django 4.2.11 on 2025-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopy", "0003_alter_entry_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controller",
            name="version",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="version"),
        ),
    ]
