# Generated by Django 4.2.11 on 2025-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopy", "0004_alter_controller_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="kind",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("email", "Email"),
                    ("textarea", "Textarea"),
                    ("text-simple", "Simple text"),
                ],
                default="text-simple",
                help_text="If you change this on an existing objects, all field and widget options will be lost.",
                max_length=50,
                verbose_name="element type",
            ),
        ),
    ]
